kind: Service
apiVersion: v1
metadata:
  name: "alert-api"
  labels:
    project: "soboon"
spec:
  selector:
    app: "alert-api"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30002
  type: NodePort
