kind: Service
apiVersion: v1
metadata:
  name: "soboon-db"
  labels:
    project: "soboon"
spec:
  selector:
    app: "soboon-db"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
  type: ClusterIP
