apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: "soboon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mysql"
  template:
    metadata:
      labels:
        app: "mysql"
        project: "soboon"
    spec:
      containers:
        - name: mysql
          image: "mysql:8.0"
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-mysql
      dnsConfig:
        options:
          - name: ndots
            value: "3"
