apiVersion: apps/v1
kind: Deployment
metadata:
  name: soboon-db
  labels:
    project: "soboon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "soboon-db"
  template:
    metadata:
      labels:
        app: "soboon-db"
        project: "soboon"
    spec:
      containers:
        - name: mysql
          image: "mysql:5.7"
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "soboon"
            - name: MYSQL_USER
              value: "Soboon"
            - name: MYSQL_PASSWORD
              value: "soboondepromeet"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-mysql
      dnsConfig:
        options:
          - name: ndots
            value: "3"
