apiVersion: apps/v1
kind: Deployment
metadata:
  name: soboon-web
  labels:
    project: "soboon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "soboon-web"
  template:
    metadata:
      labels:
        app: "soboon-web"
        project: "soboon"
    spec:
      containers:
        - name: soboon-web
          image: "yonghochoi/soboon-web"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: soboon-web
          volumeMounts:
            - mountPath: /opt/app/soboon/mysql.cnf
              name: soboon-db-mysql-cnf
              subPath: mysql.cnf
      volumes:
        - name: soboon-db-mysql-cnf
          configMap:
            name: soboon-db-mysql-cnf
            defaultMode: 420
      dnsConfig:
        options:
          - name: ndots
            value: "3"
