apiVersion: batch/v1
kind: Job
metadata:
  name: upload-to-s3
  labels:
    project: "soboon"
spec:
  template:
    spec:
      containers:
        - name: upload-to-s3
          image: "yonghochoi/soboon-web"
          command: ["/bin/sh", "-c", "cd soboon;python3 manage.py collectstatic --noinput"]
          ports:
            - containerPort: 80
              name: soboon-web
          volumeMounts:
            - mountPath: /opt/app/soboon/mysql.cnf
              name: soboon-db-mysql-cnf
              subPath: mysql.cnf
            - mountPath: /opt/app/.config_secret/settings_common.json
              name: soboon-credentials
              subPath: settings_common.json
              readOnly: true
      volumes:
        - name: soboon-db-mysql-cnf
          configMap:
            name: soboon-db-mysql-cnf
            defaultMode: 420
        - name: soboon-credentials
          secret:
            secretName: soboon-credentials
            items:
            - key: soboon-credentials
              path: settings_common.json
      restartPolicy: Never
      dnsConfig:
        options:
          - name: ndots
            value: "3"
  backoffLimit: 4
