version: 2
jobs:
  build:
    docker:
      - image: golang:1.12

    steps:
      - checkout
      - run:
          name: alert api build
          command: |
            pwd
            export GO111MODULE=on
            export GOARCH=amd64
            export GOOS=linux
            go mod tidy
            cd cmd/alertapi
            go build -o ./bin/alert-api
            ls -l
            apt-get update && \
            apt-get install -y docker.io && \
            docker --version
            cd ./bin
            cat <<EOT > Dockerfile
            FROM debian:jessie
            RUN mkdir -p /opt/soboon
            COPY ./alert-api /opt/soboon/alert-api
            RUN chmod +x /opt/soboon/alert-api
            CMD ["/opt/soboon/alert-api"]
            EOT
            ls -l
            docker build -t yonghochoi/soboon-alert-api .
            docker images
            docker push yonghochoi/soboon-alert-api

