version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/soboon

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: alert api build
          command: |
            export GO111MODULE=on
            export GOARCH=amd64
            export GOOS=linux
            go mod tidy
            cd cmd/alertapi
            go build -o ./bin/alert-api
            pwd
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          cd /go/src/soboon/cmd/alertapi/bin
          cat <<EOT > Dockerfile
          FROM debian:jessie
          RUN mkdir -p /opt/soboon
          COPY ./alert-api /opt/soboon/alert-api
          RUN chmod +x /opt/soboon/alert-api
          CMD ["/opt/soboon/alert-api"]
          EOT
          ls -l
          docker build -t yonghochoi/soboon-alert-api .
          docker images
          docker push yonghochoi/soboon-alert-api
