version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            terraform get
            terraform init
            terraform validate