version: 2
jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: alert api build
          command: |
            pwd
            export GO111MODULE=on
            export GOARCH=amd64
            export GOOS=linux
            go mod tidy
            cd cmd/alertapi
            go build -o /tmp/alert-api
      - run: |
          cd /tmp
          chmod +x alert-api
          cat <<EOT > Dockerfile
          FROM debian:jessie
          RUN mkdir -p /opt/soboon
          COPY ./alert-api /opt/soboon/alert-api
          RUN chmod +x /opt/soboon/alert-api
          CMD ["/opt/soboon/alert-api"]
          EOT
          ls -l
          docker build -t yonghochoi/soboon-alert-api .
          docker images
          docker push yonghochoi/soboon-alert-api
          docker ps