version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-go

    environment:
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux

    steps:
      - checkout # check out source code to working directory
      - run:
          name: Waiting for Postgres to be ready
          command: |
            go mod tidy
            cd cmd/alertapi
            go build -o ./bin/alert-api
            cd bin
            cat <<EOT > Dockerfile
            FROM debian:jessie
            RUN mkdir -p /opt/soboon
            COPY ./alert-api /opt/soboon/alert-api
            RUN chmod +x /opt/soboon/alert-api
            CMD ["/opt/soboon/alert-api"]
            EOT
            docker build -t soboon-alert-api .
            docker images