version: 2
jobs:
  build:
    docker:
      - image: golang:1.12

    steps:
      - checkout
      - run:
          name: alert api build
          command: |
            pwd
            export GO111MODULE=on
            export GOARCH=amd64
            export GOOS=linux
            go mod tidy
            cd cmd/alertapi
            go build -o /tmp/alert-api
      - store_artifacts:
          path: /tmp/alert-api
          destination: alert-api
  deploy:
    docker:
      - image: docker:19.03

    steps:
      - run:
          name: image build and push
          command: |
            curl https://circleci.com/api/v1.1/project/github/yonghochoi/depromeet-soboon/latest/artifacts?circle-token=$CIRCLE_TOKEN \
              | grep -o 'https://[^"]*' \
              | wget -v -i -
            chmod +x alert-api
            cat <<EOT > Dockerfile
            FROM debian:jessie
            RUN mkdir -p /opt/soboon
            COPY ./alert-api /opt/soboon/alert-api
            RUN chmod +x /opt/soboon/alert-api
            CMD ["/opt/soboon/alert-api"]
            EOT
            ls -l
            docker build -t yonghochoi/soboon-alert-api .
            docker images
            docker push yonghochoi/soboon-alert-api