version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run:
          name: alert api build
          command: |
            export GO111MODULE=on
            export GOARCH=amd64
            export GOOS=linux
            go mod tidy
            cd cmd/alertapi
            go build -o ./bin/alert-api
            cd bin
            cat <<EOT > Dockerfile
            FROM debian:jessie
            RUN mkdir -p /opt/soboon
            COPY ./alert-api /opt/soboon/alert-api
            RUN chmod +x /opt/soboon/alert-api
            CMD ["/opt/soboon/alert-api"]
            EOT
            docker build -t soboon-alert-api .
            docker images