apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      fields.application: ${APP}
      paths:
        - /var/log/${APP}.log
    processors:
    - add_cloud_metadata: ~
    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_END_POINT}"]